
LABEL authors="Robrecht Cannoodt <robrecht@data-intuitive.com>" \
    org.opencontainers.image.description="Docker image containing the dependencies for running the BD Rhapsody pipeline" \
    org.opencontainers.image.source="https://github.com/data-intuitive/ghcr_cellranger"

# update packages
RUN apt-get --allow-releaseinfo-change update && \
  apt upgrade -y

# update picard
RUN conda update --no-channel-priority -y -c bioconda picard

# install procps and nodejs
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y procps nodejs && \
  rm -rf /var/lib/apt/lists/*

# install cwl-runner
RUN pip install --upgrade pip && \
  pip install --upgrade --no-cache-dir "cwlref-runner" "cwl-runner" "ruamel.yaml"